import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

/*
in Next.js, if you have a layout.tsx in a folder, Next.js automatically use it as a wrapper for all pages in that folder
hence children is set to the page.tsx output

in the app router (/app folder)
- layout defines wrapper for all pages and layouts beneath it
- page defines the actual route content for that folder
*/

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> 
        <DashboardWrapper>{children}</DashboardWrapper>
      </body>
    </html>
  );
}
